### ISSUE TITLE
`route_response_latency_ms` histogram inbound metrics no longer exposed

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#10521]
I verified this started to happen on edge-23.3.1 (proxy v2.191.2).

## Repro

```bash
# install the booksapp injected
$ kubectl create ns booksapp && \
  linkerd inject https://run.linkerd.io/booksapp.yml \
  | kubectl -n booksapp apply -f -

# install the webapp ServiceProfile
$ curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/booksapp/webapp.swagger \
  | linkerd -n booksapp profile --open-api - webapp \
  | kubectl -n booksapp apply -f -

# viz routes is empty (this also affects the Routes Metrics tab in the dashboard)
$ linkerd viz -n booksapp routes deploy/webapp
ROUTE                       SERVICE   SUCCESS   RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
GET /                        webapp         -     -             -             -             -
GET /authors/{id}            webapp         -     -             -             -             -
GET /books/{id}              webapp         -     -             -             -             -
POST /authors                webapp         -     -             -             -             -
POST /authors/{id}/delete    webapp         -     -             -             -             -
POST /authors/{id}/edit      webapp         -     -             -             -             -
POST /books                  webapp         -     -             -             -             -
POST /books/{id}/delete      webapp         -     -             -             -             -
POST /books/{id}/edit        webapp         -     -             -             -             -
[DEFAULT]                    webapp         -     -             -             -             -

# the metric only has entries for the outbound label
$ linkerd diagnostics proxy-metrics -n booksapp deploy/webapp | grep route_response_latency_ms_bucket
route_response_latency_ms_bucket{direction="outbound",dst="books.booksapp.svc.cluster.local:7002",status_code="200",le="1"} 263
route_response_latency_ms_bucket{direction="outbound",dst="books.booksapp.svc.cluster.local:7002",status_code="200",le="2"} 321
route_response_latency_ms_bucket{direction="outbound",dst="books.booksapp.svc.cluster.local:7002",status_code="200",le="3"} 326
route_response_latency_ms_bucket{direction="outbound",dst="books.booksapp.svc.cluster.local:7002",status_code="200",le="4"} 326
--snip--
```

**Comment by alpeb** [comment]
It appears the issue was introduced in linkerd/linkerd2-proxy#2250 in [logical.rs](https://github.com/linkerd/linkerd2-proxy/pull/2250/files#diff-3a134db02431d90e120090fa92c06e64064c33fc1cd218c9330af36cda83f31b) with the removal of `.push(http::NewHeaderFromTarget::<CanonicalDstHeader, (), _>::layer())`. Now `CanonicalDstHeader` isn't used anywhere.

**Comment by hawkw** [comment]
https://github.com/linkerd/linkerd2-proxy/pull/2383 should fix this.

**Comment by hawkw** [comment]
Proxy release v2.197.1 (merged in #10711) added the change fixing this.

**Comment by alpeb** [comment]
It appears this bug has resurfaced as of `stable-2.13.1` (proxy at `2.198.1`). The interesting part is that the metrics are not exposed when the ServiceProfile is created _after_ the workloads have been injected. When injected workloads start running with a pre-existing ServiceProfile, the metrics are exposed.

## Repro

```bash
$ k3d cluster create
$ curl -sL https://run.linkerd.io/install | LINKERD2_VERSION=stable-2.13.1 sh
$ linkerd install --crds | kubectl apply -f -
$ linkerd install | kubectl apply -f -
$ linkerd viz install | kubectl apply -f -
# wait for viz to be running
$ kubectl create ns booksapp
$ linkerd inject https://run.linkerd.io/booksapp.yml | kubectl apply -f -
$ curl https://run.linkerd.io/booksapp/webapp.swagger \
  | linkerd -n booksapp profile --open-api - webapp \
  | kubectl -n booksapp apply -f -
$ linkerd viz tap -n booksapp deploy/webapp -ojson|grep -A 1 l5d-dst-canonical
[empty response]
$ kubectl -n booksapp rollout restart deploy
$ linkerd viz tap -n booksapp deploy/webapp -ojson|grep -A 1 l5d-dst-canonical
        "name": "l5d-dst-canonical",
        "valueStr": "webapp.booksapp.svc.cluster.local:7000"
...
```

**Comment by alpeb** [comment]
Offline conversation revealed that this is happening because already established connections are put on "HTTPRoute" mode, which doesn't take into account ServiceProfiles that are setup after the fact. Once the connection is reset, ServiceProfiles are accounted for again and we start seeing the `l5d-dst-canonical` header and the route metrics.

To test this by resetting that connection without having to restart the web pod, one can instead bounce the `traffic` pod.

**Comment by johnjeffers** [comment]
Has there been any action on this? I'm still seeing the problem. I've upgraded to 2.13.4.

**Comment by johnjeffers** [comment]
Does anyone have any info about this?

**Comment by risingspiral** [comment]
Hey @johnjeffers. Thanks for reaching out. The problem initially described in this issue has been addressed. The current system behavior is as expected. When a service is discovered, if there are no existing ServiceProfiles describing a Service, then the proxy defaults to using HTTPRoute-based outbound policies for that Service, and stores a default policy in the proxy’s cache. This existing policy is not replaced just by the ServiceProfile creation event. The proxy will discover the ServiceProfile-based policy if the pod is rolled or if the proxy’s cache entry for the target service is evicted due to timeout (defaults to 5 seconds of no requests). Improvements to this situation for route-based policy are planned for 2.14. You can follow that here: https://github.com/linkerd/linkerd2/issues/11032

**Comment by johnjeffers** [comment]
Restarting the pods doesn't seem to fix it for me. Is there anything else I can try?
