### ISSUE TITLE
kubeconfig using server paths does not work with tap

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3558]
### What is the issue?

Given a kubeconfig with `clusters[0].cluster.server = https://localhost:8443/k8s/clusters/c-c6rsk`, `linkerd tap` always fails with a 404. The URL being fetched is `/apis/tap.linkerd.io/v1alpha1/namespaces/default/deployments/tap` and should be `/k8s/clusters/c-c6rsk/apis/tap.linkerd.io/v1alpha1/namespaces/default/deployments/tap`

### How can it be reproduced?

Stand up a rancher cluster with all default settings.

**Comment by ihcsim** [comment]
fwiw, I remember helping a user with a similar problem. `kubectl proxy` won't work if `clusters[0].cluster.server = https://<hostname>:<port>/<some-path>` where `<some-path>` needs to be prepended to `/apis/tap.linkerd.io/v1alpha1/namespaces/foo`. An issue was raised at https://github.com/kubernetes/kubectl/issues/715, as it didn't look like a Linkerd issue.

**Comment by grampelberg** [comment]
It definitely works for APIServices and `kubectl` (at least 1.16) as that's how I figured out how it was broken to begin with.

**Comment by pietervogelaar** [comment]
A possible related problem. I have Rancher v2.2.8 and installed a default Kubernetes cluster with Rancher.

With helm 3, I installed linkerd2 `edge-19.9.4`. Installation works great. After running `helm upgrade --install` I get:

```
Release "linkerd" has been upgraded. Happy Helming!
NAME: linkerd
LAST DEPLOYED: Thu Oct 10 17:59:20 2019
NAMESPACE: linkerd
STATUS: deployed
REVISION: 2
NOTES:
The Linkerd control plane was successfully installed 🎉

To help you manage your Linkerd service mesh you can install the Linkerd CLI by running:

  curl -sL https://run.linkerd.io/install | sh

Alternatively, you can download the CLI directly via the Linkerd releases page:

  https://github.com/linkerd/linkerd2/releases/

Looking for more? Visit https://linkerd.io/2/getting-started/
```

However after this, it never works again. Every time I execute `helm upgrade --install` I get:
```
Error: UPGRADE FAILED: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: tap.linkerd.io/v1alpha1: the server is currently unable to handle the request
```

**Comment by pietervogelaar** [comment]
This line https://github.com/linkerd/linkerd2/blob/0f9ea553d2ab9b985e6d9666e95dae2260c26210/pkg/tap/tap.go#L40 must be:

```
url.Path = path.Join(url.Path, protohttp.TapReqToURL(req))
```

After that it says:
```
./bin/go-run cli tap -n ambassador deploy/ambassador --verbose
DEBU[0000] Response from [https://rancher.localdev/k8s/clusters/c-wwnf8/apis/tap.linkerd.io/v1alpha1/watch/namespaces/ambassador/deployments/ambassador/tap] had headers: map[Content-Length:[45] Content-Type:[application/octet-stream] Date:[Thu, 24 Oct 2019 15:45:04 GMT] Linkerd-Error:[Internal Server Error] Server:[openresty/1.15.8.1] Strict-Transport-Security:[max-age=15724800; includeSubDomains]]
Error: no pods found for deployment/ambassador
Usage:
  linkerd tap [flags] (RESOURCE)
...
```
However `kubectl get pods -n ambassador` says:
```
NAME                          READY   STATUS    RESTARTS   AGE
ambassador-589cd96449-7zdns   2/2     Running   0          3h1m
ambassador-589cd96449-l8drp   2/2     Running   0          3h1m
ambassador-589cd96449-v8fzv   2/2     Running   0          3h1m
```

**Comment by KIVagant** [comment]
I've saw the same issue in [Velero](https://velero.io) where it was not critical at that moment. But today I upgraded Helm from 2.14 to 2.16 in the cluster and now helm stopped working. Are there any workarounds available? Is it safe to temporary delete the ApiService (and disable its creation in the Helm chart) or it will affect Linkerd? We can survive without linkerd tap for a while, but not without Helm. :(

**Comment by base698** [comment]
Looks like the kubectl issue was closed.  Is there a workaround?

**Comment by grampelberg** [comment]
@base698 it should be fixed.

**Comment by base698** [comment]
@grampelberg What version of linkerd/kubectl?  

Still a problem in 2.7.1

**Comment by grampelberg** [comment]
Umm, an edge after 20.3.1 or so.

**Comment by cpretzer** [comment]
@base698 the edge versions are `edge-YY-MM-N` where `N` is the release number in the month.

You can find all the releases here: https://github.com/linkerd/linkerd2/releases

**Comment by grampelberg** [comment]
Also https://linkerd.io/2/edge/ for the docs.
