### ISSUE TITLE
proxy error:client requires absolute-form URIs

### ISSUE THREAD

**Issue by n-oden** [linkerd/linkerd2#5298]
### What is the issue?

~15 hours after upgrading our staging cluster from edge-20.7.5 to stable-2.9.0, we observed connectivity errors between multiple pods in the same namespace that normally communicate over k8s services.  From the perspective of the client, all requests to `http://server/foo` were returned instantly with a 502 error, while the linkerd-proxy log on both the client and server reported e.g:

```
[  8109.623316s]  WARN ThreadId(01) inbound:accept{peer.addr=10.4.2.144:50078 target.addr=10.4.2.205:3000}: linkerd2_app_core::errors: Failed to proxy request: client requires absolute-form URIs
```

Note that the pods were _not_ restarted after the linkerd update, so while the control plane was running 2.9.0, the pods were still running the older version of the proxy.

Interestingly, if from the client pod I manually curl `http://server.namespace/foo` rather than `http://server/foo` the request succeeds; it's only the un-qualified version of the URL that fails.

### How can it be reproduced?

At least for us, the repro path is to update from the old edge release to the new stable release and then wait 12-24 hours; it's happened twice so far.  That said I do not know what level of traffic (if any) might be necessary to trigger it and there is no obvious reason why the issue starts when it does.

#### `linkerd check` output

Pre-update: 

```text
$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.7.1 but the latest stable version is 2.9.0
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 20.7.5 but the latest edge version is 20.11.5
    see https://linkerd.io/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running edge-20.7.5 but cli running stable-2.7.1
    see https://linkerd.io/checks/#l5d-version-control for hints

Status check results are √```

### Environment

- Kubernetes Version: 1.16.15-gke.4300
- Cluster Environment: GKE
- Host OS: Google Container-Optimized OS (cos)
- Linkerd version: edge-20.7.5; stable-2.9.0

**Comment by olix0r** [comment]
> Note that the pods were not restarted after the linkerd update, so while the control plane was running 2.9.0, the pods were still running the older version of the proxy.

So, to confirm: the server proxy is version `edge-20.7.5`?

I'm having a really hard time coming up with a hypothesis about how the control plane version change could cause this error... the control plane isn't involved at all in determining whether absolute-form clients are used. This sounds a lot more like a client caching issue, sort of like linkerd/linkerd2#5069 -- though I don't think the bug this fixed as introduced until after edge-20.7.5. 

For example, I could understand an issue where a service gets a request in the absolute from (e.g. `GET http://foo.bar.../ HTTP/1.1`), caches the client for that form, and then tries to reuse it when a relative-form request comes in (e.g. `GET / HTTP/1.1`) -- this could also explain why issuing a request with a different URI might avoid the problem, since the clients are cached by logical destination in 20.7.5. And with the 12-15 hour time to repro, this could be caused by some very sporadic requests... Perhaps this issue is reproducible at specific _times_ (not relative to the control plane upgrade)?

Almost all of the client caching code has changed since then; so if there is a bug in edge-20.7.5, it likely would not exist in newer proxy versions. Is it feasible to restart application pods to pick up the updated proxy version? If it takes 12+ hours to reproduce this during an upgrade, is it possible to just avoid the issue?

If you do want to spend more time diagnosing this, I'd recommend running the server with `config.linkerd.io/proxy-log-level: linkerd=debug,warn` this should give us enough metadata about the cache keys to understand what's going on; but I'm a bit skeptical about this bug being related to the upgrade if all application pods are using the old proxy version. And even if it is somehow caused by a weird interaction between the older proxies and the newer control plane, I'm not confident that we could provide a fix that doesn't involve updating the older proxies...

**Comment by kivagant-ba** [comment]
We run into the same issue. It probably happens when some pods get a `stable-2.9.0` proxy while older pods still have _some of the older versions_ (in our case it is `2.7.1`).

**Comment by olix0r** [comment]
I'd be especially curious to see the output of a proxy with a log level like `linkerd2=debug,linkerd2_proxy_http=trace`.

The code in question is here: https://github.com/linkerd/linkerd2-proxy/blob/100a6b324452442837f9fae122c82584d87bd54a/linkerd%2Fproxy%2Fhttp%2Fsrc%2Fh1.rs#L106-L107

It sounds like we're somehow incorrectly marking a client in absolute-form? It seems less likely--though entirely possible, I guess--that we're actually handling absolute-form requests. But it would be helpful to start narrowing down the exact interactions that trigger this.

**Comment by olix0r** [comment]
I spent some time trying to reproduce this manually by sending a mix of absolute-form and relative-form requests, but this wasn't enough to trigger the issue. If someone has a reproducible case, I'd be especially eager to capture the log messages from the modules `linkerd2_proxy_http::h1` and `linkerd2_proxy_http::normalize_uri` (at trace level, per the above-mentioned log configuration).

**Comment by lundbird** [comment]
We also ran into this issue with out setup. The warn message above was intermittent but caused 502 in the injected apps. Fixing was as simple as restarting the existing injected applications to ensure they get the latest proxy sidecar.

**Comment by svmaris** [comment]
We've had the same issue when we upgraded from 2.8.1 to 2.9.0. The control plane was updated, *some* pods were restarted and got the new proxy, but some didn't (which was our own fault btw).

Using curl from an unmeshed Alpine pod worked fine, but requests coming from another pod failed with the reported error. So I *think* this only occurs when a 2.9.0-enabled Pod talks to a service that's still on 2.8.0.

Also, and this might be a coincidence, but in both instances we got the errors, it was a Go HTTP Client from within the mesh doing the request (one from Grafana to Loki and the other from one of our own Go services to another one)... all of the other requests were working just fine.

**Comment by byrnedo** [comment]
We also get this when a 2.8.1 proxied pod tries to talk to a 2.9.0 proxied pod.

**Comment by behrtam** [comment]
+1 with 2.8.1 to 2.9.0 proxied pod

**Comment by adinhodovic** [comment]
What's the approach to avoid downtime/5xx error while upgrading from 2.8.1 to 2.9.1/2? Just ran into the same issue in our staging environment. Should data planes not be backward compatible by at least 1 version? Did anyone find a workaround?

**Comment by wmorgan** [comment]
@adinhodovic Yes, data planes *should* always be compatible by one stable version. In this case there appears to be a bug in some calls that we haven't been able to reproduce. Are you able to reproduce it consistently in your staging environment? If so, can you enable trace logging and report the relevant log lines from `linkerd2_proxy_http::h1` and `linkerd2_proxy_http::normalize_uri` modules?

**Comment by olix0r** [comment]
I've got this repro'd now.

1. install linkerd stable-2.8.1
2. deploy an app (i used a [load generator](https://github.com/olix0r/ort) i wrote, configured to send 1 http request every 5s).
3. upgrade the control plane to linkerd stable-2.9.2
4. restart the server to pick up the newer proxy
5. Then the server emits log messages including the error.

**Comment by adinhodovic** [comment]
> @adinhodovic Yes, data planes _should_ always be compatible by one stable version. In this case there appears to be a bug in some calls that we haven't been able to reproduce. Are you able to reproduce it consistently in your staging environment? If so, can you enable trace logging and report the relevant log lines from `linkerd2_proxy_http::h1` and `linkerd2_proxy_http::normalize_uri` modules?

@wmorgan Ran into this error today and have not had the time yet, but could make a effort if @olix0r repro is not enough. Would be great to backport a fix since it will allow a smooth upgrade for us.

**Comment by wmorgan** [comment]
@adinhodovic Appreciate the offer. Given @olix0r's repro (woot!) we're probably in good shape but I'll let him chime in if he wants more logs.

**Comment by mihdih** [comment]
We ran into this problem just recently when we've upgraded 2.8.1 -> 2.9.2. Able to reproduce the issue locally which is essentially similar to what @olix0r described. 

- **client** (named: `alpha`) running proxy 2.8.1
- **server** (named: `beta`) running proxy 2.9.2 after a restart
- performed curl command from **client**: 
```
$ curl -I -s http://beta.default.svc.cluster.local
HTTP/1.1 502 Bad Gateway
content-length: 0
date: Fri, 29 Jan 2021 00:45:48 GMT
```
- query from `beta` to `alpha` works
```
$ curl -I -s http://alpha.default.svc.cluster.local
HTTP/1.1 200 OK
server: nginx/1.14.0 (Ubuntu)
date: Fri, 29 Jan 2021 00:45:57 GMT
content-type: text/html
content-length: 612
last-modified: Thu, 28 Jan 2021 22:52:32 GMT
accept-ranges: bytes
etag: "60134030-264"
```
Attaching logs for reference. 
[alpha-2.8.1-pod.log](https://github.com/linkerd/linkerd2/files/5890880/alpha-2.8.1-pod.log)
[beta-2.9.2-pod.log](https://github.com/linkerd/linkerd2/files/5890883/beta-2.9.2-pod.log)

**Comment by olix0r** [comment]
This is fixed in the latest edge release and we'll be releasing a backported fix as stable-2.9.3 next week.

**Comment by mihdih** [comment]
Hello, once again thank you for the release of linkerd 2.9.3. Just recently we tried to update our cluster again from version 2.8.1 to 2.9.3. However same as before we still noticed the same problem. Where in, services that are still running proxy 2.8.1 failed to establish http connection to services that are running with 2.9.3 proxy. This happened in our UAT EKS cluster with version k8s 1.18.

To further test the issue and ensuring that it was not due to underlaying cluster setup. I tried to replicate it in my local machine using k8s(1.16.6) on docker desktop, and sadly same behaviour.

Below are the steps to replicate.

- Install linkerd 2.8.1 from scratch (`linkerd install | kubectl apply -f - `) 
- Deployed test services (nginx or httpd). (**app1**, **app2**, **app3** in my case)
- Expose each with their corresponding service (`app1.default.svc.cluster.local`, `app2.default.svc.cluster.local`, `app3.default.svc.cluster.local`)
- At this state when tested, as expected no issue as all are running the same proxy (2.8.1)
- Upgrade linkerd to 2.9.3 (`linkerd upgrade | kubectl apply -f - `)
- Rolling restart app2 and app3 (`kubectl rollout restart deployment/app{2,3}`)
- **app1** yields 502 when invoke curl against both **app2** and **app3**

I am not sure what i am missing here, is there other step that needs to be considered when doing the upgrade from 2.8.1 -> 2.9.3?

Linkerd proxy check
```
linkerd-data-plane
------------------
√ data plane namespace exists
√ data plane proxies are ready
√ data plane proxy metrics are present in Prometheus
‼ data plane is up-to-date
    Some data plane pods are not running the current version:
	* default/app1-6fcb445b46-pgzsc (stable-2.8.1)
    see https://linkerd.io/checks/#l5d-data-plane-version for hints
‼ data plane and cli versions match
    default/app1-6fcb445b46-pgzsc running stable-2.8.1 but cli running stable-2.9.3
    see https://linkerd.io/checks/#l5d-data-plane-cli-version for hints
```
I have attached the logs of the `linkerd-proxy` of the 3 apps for reference.

[app1-trace.log](https://github.com/linkerd/linkerd2/files/5998716/app1-trace.log)
[app2-trace.log](https://github.com/linkerd/linkerd2/files/5998718/app2-trace.log)
[app3-trace.log](https://github.com/linkerd/linkerd2/files/5998719/app3-trace.log)

**Comment by adinhodovic** [comment]
Just ran an update on one of our staging clusters from 2.8.1 to 2.9.3. Still have the same issues and identical to @mihdih's report. Thanks for 2.9.3 but still find the 2.9 data plane to be incompatible with <2.9.

**Comment by byrnedo** [comment]
We're also rolling back to 2.8 because of this again.

**Comment by olix0r** [comment]
I'm able to reproduce this. My sincere apologies and thanks for reporting this. We'll fix this.

**Comment by olix0r** [comment]
So, it turns out that, while we did fix this in the proxy and backport the fix onto the 2.9.x version of the proxy, this fixed version isn't what was actually tagged for release:

```
commit ee3fa1483a51a3e3414a23e51d6ef0b02c30098c (tag: release/v2.124.1, tag: release/v2.124.0)
```

The proxy tag release/v2.124.0 is what was used for 2.9.0; and the release/v2.124.0 tag points to the same commit 😞 

We'll create a v2.124.2 tag on the proper commit (d1766c00) and confirm the fix for a stable-2.9.4.

Again, my apologies for the confusion.

**Comment by ericsuhong** [comment]
We faced the same issue when we upgrade from 2.8.1 to 2.9.3. We will revert and wait for stable 2.9.4 release!

Thanks.

**Comment by olix0r** [comment]
[stable-2.9.4](https://github.com/linkerd/linkerd2/releases/tag/stable-2.9.4) has been released and is available via
```
:; curl -sL https://run.linkerd.io/install |sh -
```

I've confirmed that the fix is included via:
```
# Create a k3d cluster with a version that supports Linkerd 2.8.1
:; k3d cluster create --image rancher/k3s:v1.18.9-k3s1

# Install 2.8.1
:; ~/.linkerd2/bin/linkerd-stable-2.8.1 install | k apply -f -

# Run emojivoto
:; curl -sL https://run.linkerd.io/emojivoto.yml | ~/.linkerd2/bin/linkerd-stable-2.8.1 inject - | k apply -f -

# Confirm the installed version is 2.9.4 before upgrading
:; linkerd version
Client version: stable-2.9.4
Server version: stable-2.8.1

# Upgrade the control plane
:; linkerd upgrade | k apply -f -

# ... wait for the control plane upgrade to complete ...

# Restart only emojivoto's `web` deployment
:; k rollout restart -n emojivoto deploy/web

# Confirm traffic is flowing through the restarted pod
:; linkerd stat -n emojivoto deploy
NAME       MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TCP_CONN
emoji         1/1   100.00%   2.0rps           1ms           1ms           1ms          2
vote-bot      1/1         -        -             -             -             -          -
voting        1/1    86.67%   1.0rps           1ms           1ms           1ms          2
web           1/1    94.38%   1.5rps           2ms           3ms           3ms          2

# Ensure no errors in the proxy logs
:; k logs -n emojivoto deploy/web -c linkerd-proxy
time="2021-02-24T00:54:50Z" level=info msg="running version stable-2.9.4"
[     0.000578s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.000949s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.000957s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.000959s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.000960s]  INFO ThreadId(01) linkerd2_proxy: Tap interface on 0.0.0.0:4190
[     0.000962s]  INFO ThreadId(01) linkerd2_proxy: Local identity is web.emojivoto.serviceaccount.identity.linkerd.cluster.local
[     0.000966s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.000968s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.001111s]  INFO ThreadId(01) outbound: linkerd2_app: listen.addr=127.0.0.1:4140 ingress_mode=false
[     0.001151s]  INFO ThreadId(01) inbound: linkerd2_app: listen.addr=0.0.0.0:4143
[     0.011597s]  INFO ThreadId(02) daemon:identity: linkerd2_app: Certified identity: web.emojivoto.serviceaccount.identity.linkerd.cluster.local
```

Please let us know if you see anything unexpected with stable-2.9.4!

**Comment by mihdih** [comment]
By the way I can confirmed that this is now working. Tried it locally and it worked (using linkerd 2.9.4). Thanks again
