### ISSUE TITLE
Linkerd proxy killed with OOM

### ISSUE THREAD

**Issue by fpetkovski** [linkerd/linkerd2#5764]
### What is the issue?
The linkerd proxy is getting killed with OOM on regular basis. However, the memory usage before the proxy is killed is stable at ~6MB. We see neither memory creep nor spikes. The problem might be that the proxy is trying to allocate a lot of memory at once or in a very short period of time, which is why the high usage is not reflected in our monitoring system.

### How can it be reproduced?
We are unable to reproduce this issue in a controlled manner, but it happens sporadically in all of our environments.

### Logs, error output, etc
Here is a log of kubectl describe showing the status of the `linkerd-proxy` container:
```  linkerd-proxy:
    Container ID:  docker://1ad8fc58b8e58274586048c433063bdfbe3f0ee05c59c0aeec9e947c1df7755d
    Image:         824725208937.dkr.ecr.eu-central-1.amazonaws.com/linkerd2-proxy:v2.132.0-no-authority
    Image ID:      docker-pullable://824725208937.dkr.ecr.eu-central-1.amazonaws.com/linkerd2-proxy@sha256:50d010db0648bfcad10c32f859497978ac1bf8e00d843c279e5c18c9b9962c16
    Ports:         4143/TCP, 4191/TCP
    Host Ports:    0/TCP, 0/TCP
    State:         Running
      Started:     Wed, 17 Feb 2021 12:23:06 +0100
    Last State:    Terminated
      Reason:      OOMKilled
      Message:     time="2021-02-17T11:22:47Z" level=info msg="running version edge-21.1.2"
time="2021-02-17T11:22:47Z" level=info msg="Found pre-existing key: /var/run/linkerd/identity/end-entity/key.p8"
time="2021-02-17T11:22:47Z" level=info msg="Found pre-existing CSR: /var/run/linkerd/identity/end-entity/csr.der"
[     0.001847s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.002386s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.002403s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.002405s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.002407s]  INFO ThreadId(01) linkerd2_proxy: Tap interface on 0.0.0.0:4190
[     0.002409s]  INFO ThreadId(01) linkerd2_proxy: Local identity is default.stage.serviceaccount.identity.linkerd.cluster.local
[     0.002412s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.002414s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.002567s]  INFO ThreadId(01) outbound: linkerd_app: listen.addr=127.0.0.1:4140 ingress_mode=false
[     0.002695s]  INFO ThreadId(01) inbound: linkerd_app: listen.addr=0.0.0.0:4143
[     0.018728s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity: default.stage.serviceaccount.identity.linkerd.cluster.local
      Exit Code:    137
      Started:      Wed, 17 Feb 2021 12:22:47 +0100
      Finished:     Wed, 17 Feb 2021 12:22:51 +0100
    Ready:          True
    Restart Count:  2
    Limits:
      memory:  250Mi
    Requests:
      cpu:      100m
      memory:   250Mi
```

#### `linkerd check` output

```text
fp@sync > linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-04-02T16:06:37Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.9.2 but the latest stable version is 2.9.3
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.9.2 but the latest stable version is 2.9.3
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

```

### Environment

- Kubernetes Version: v1.18.9
- Cluster Environment: EKS
- Host OS: Amazon Linux 2
- Linkerd version: 2.9.2
- Linkerd proxy version: edge-21.1.2

**Comment by olix0r** [comment]
@fpetkovski Can you share any details about the traffic on these pods?

**Comment by fpetkovski** [comment]
This particular pod servers HTTP traffic with less than 50RPS. What might be easier to troubleshoot for you guys is the linkerd-proxy container that is part of the identity pod. This one has restarted 3 times:
```
  linkerd-proxy:
    Container ID:  docker://99571653393b808d259a774a0810378d33fdebef49b92fc3d701d6671a71572c
    Image:         824725208937.dkr.ecr.eu-central-1.amazonaws.com/linkerd2-proxy:v2.132.0-no-authority
    Image ID:      docker-pullable://824725208937.dkr.ecr.eu-central-1.amazonaws.com/linkerd2-proxy@sha256:50d010db0648bfcad10c32f859497978ac1bf8e00d843c279e5c18c9b9962c16
    Ports:         4143/TCP, 4191/TCP
    Host Ports:    0/TCP, 0/TCP
    State:         Running
      Started:     Mon, 15 Feb 2021 09:31:30 +0100
    Last State:    Terminated
      Reason:      OOMKilled
      Message:     readId(01) inbound:accept{peer.addr=10.250.178.54:57400 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=server: Connection reset by peer (os error 104)
[ 85945.734225s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.144.153:57956 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=server: Connection reset by peer (os error 104)
[ 85945.737790s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.147.99:42586 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=server: Connection reset by peer (os error 104)
[ 85945.745260s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.154.70:37966 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=server: Connection reset by peer (os error 104)
[ 86018.292044s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.155.85:55648 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=server: Connection reset by peer (os error 104)
[ 86027.871370s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.180.162:59400 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
[ 86028.315427s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.148.255:54046 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=server: Connection reset by peer (os error 104)
[ 86267.972787s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.148.117:52682 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=server: Connection reset by peer (os error 104)
[ 86268.479610s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.158.212:35132 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=server: Connection reset by peer (os error 104)
[ 86277.902468s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.178.50:40078 target.addr=10.250.149.182:8080}: linkerd_app_core::serve: Connection closed error=TLS detection timeout

      Exit Code:    137
      Started:      Sun, 14 Feb 2021 09:30:51 +0100
      Finished:     Mon, 15 Feb 2021 09:31:29 +0100
    Ready:          True
    Restart Count:  3
    Limits:
      memory:  250Mi
    Requests:
      cpu:      100m
      memory:   250Mi
    Liveness:   http-get http://:4191/live delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:4191/ready delay=2s timeout=1s period=10s #success=1 #failure=3

```

**Comment by fpetkovski** [comment]
We have a new finding from today's restarts. We consistently observe a spike in open file descriptors before the OOM event happens. The proxy in a linkerd-sp-validator pod restarted at exactly 07:38:55 which is also when the file descriptor count rapidly increased:

![image](https://user-images.githubusercontent.com/1286231/108331717-54cfb700-71cf-11eb-98dc-f74fa5823d86.png)

kubectl describe logs
```
  linkerd-proxy:
    Container ID:  docker://fd87216f2630c7047e9769b1120500b1b200e071998ebe0a45130b0757ca9d33
    Image:         824725208937.dkr.ecr.eu-central-1.amazonaws.com/linkerd2-proxy:v2.132.0-no-authority
    Image ID:      docker-pullable://824725208937.dkr.ecr.eu-central-1.amazonaws.com/linkerd2-proxy@sha256:50d010db0648bfcad10c32f859497978ac1bf8e00d843c279e5c18c9b9962c16
    Ports:         4143/TCP, 4191/TCP
    Host Ports:    0/TCP, 0/TCP
    State:         Running
      Started:     Thu, 18 Feb 2021 07:39:06 +0100
    Last State:    Terminated
      Reason:      OOMKilled
      Message:     n closed error=connection closed before message completed
[    19.886690s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:49765 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[    19.891020s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:49809 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[    19.891391s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:49851 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[    19.895871s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:49897 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[    19.896320s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:49941 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[    19.900545s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:49987 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[    19.900892s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:50033 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[    19.905390s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:50081 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[    19.905722s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:50131 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[    19.910100s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:50189 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed

      Exit Code:    137
      Started:      Thu, 18 Feb 2021 07:37:54 +0100
      Finished:     Thu, 18 Feb 2021 07:38:55 +0100
    Ready:          True
    Restart Count:  2
    Limits:
      memory:  250Mi
    Requests:
      cpu:      100m
      memory:   250Mi
```

**Comment by olix0r** [comment]
@fpetkovskiIn This last example shows something surprising:

```
[    19.886690s]  INFO ThreadId(01) outbound:accept{peer.addr=127.0.0.1:49765 target.addr=127.0.0.1:4140}: linkerd_app_core::serve: Connection closed error=connection closed before message completed
```

This indicates a traffic loop. That is, the outbound proxy is attempting to connect to `127.0.0.1:4140` -- the inbound proxy. We should look into doing more to defend against this situation, but I can't really figure out how you'd get into this state. If this output is from the `sp-validator` component, this is especially confusing, as, as far as i know, there shouldn't even outbound connections from this controller.

I also notice that you're using a custom proxy image:
```
    Image:         824725208937.dkr.ecr.eu-central-1.amazonaws.com/linkerd2-proxy:v2.132.0-no-authority
```

Can you share the changes you've made?

**Comment by fpetkovski** [comment]
@olix0r 

> I also notice that you're using a custom proxy image:
> 
> ```
>     Image:         824725208937.dkr.ecr.eu-central-1.amazonaws.com/linkerd2-proxy:v2.132.0-no-authority
> ```
> 
> Can you share the changes you've made?

Sure thing, I pushed the image to a public registry `fpetkovski/linkerd2-proxy:v2.132.0-no-authority`. This image is based on v2.132.0 and we just hardcoded the authority label to work around the issue described in https://github.com/linkerd/linkerd2/issues/5746. You can see the diff here: https://github.com/linkerd/linkerd2-proxy/compare/release/v2.132.0...fpetkovski:release/v2.132.0-no-authority?expand=1

> If this output is from the sp-validator component, this is especially confusing, as, as far as i know, there shouldn't ever be outbound connections from this controller.

Could this be indicating a connection failure to other control plane components like `destination` and `identity`? We've had several data plane issues caused by failures in `destination`. It might also be the reason why the container lives for such a short time, just a bit longer than a minute.

> Also, if you have prior logs from this pod, are there any errors on the `inbound` proxy?

The error message "connection closed before message completed"  appears ~6000 times. Here are all of the logs excluding that particular one:
```

  | 2021-02-18 07:38:13.586 | [    18.910168s]  INFO ThreadId(02) daemon:tap:accept{peer.addr=10.250.145.146:58546 target.addr=10.250.149.30:4190}: linkerd_app_core::serve: Connection closed error=http2 error: protocol error: unspecific protocol error detected

  | 2021-02-18 07:38:13.585 | [    18.909286s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.145.146:56676 target.addr=10.250.149.30:4143}: linkerd_app_core::serve: Connection closed error=Direct connections must be mutually authenticated

  | 2021-02-18 07:38:13.585 | [    18.909762s]  INFO ThreadId(02) daemon:tap:accept{peer.addr=10.250.145.146:58544 target.addr=10.250.149.30:4190}: linkerd_app_core::serve: Connection closed error=http2 error: protocol error: unspecific protocol error detected

  | 2021-02-18 07:38:13.580 | [    18.905088s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.145.146:56672 target.addr=10.250.149.30:4143}: linkerd_app_core::serve: Connection closed error=Direct connections must be mutually authenticated

  | 2021-02-18 07:37:54.702 | [     0.026135s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity: linkerd-sp-validator.linkerd.serviceaccount.identity.linkerd.cluster.local

  | 2021-02-18 07:37:54.679 | [     0.003293s]  INFO ThreadId(01) inbound: linkerd_app: listen.addr=0.0.0.0:4143

  | 2021-02-18 07:37:54.678 | [     0.002371s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime

  | 2021-02-18 07:37:54.678 | [     0.002763s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191

  | 2021-02-18 07:37:54.678 | [     0.002780s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143

  | 2021-02-18 07:37:54.678 | [     0.002782s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140

  | 2021-02-18 07:37:54.678 | [     0.002784s]  INFO ThreadId(01) linkerd2_proxy: Tap interface on 0.0.0.0:4190

  | 2021-02-18 07:37:54.678 | [     0.002786s]  INFO ThreadId(01) linkerd2_proxy: Local identity is linkerd-sp-validator.linkerd.serviceaccount.identity.linkerd.cluster.local

  | 2021-02-18 07:37:54.678 | [     0.002790s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)

  | 2021-02-18 07:37:54.678 | [     0.002788s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)

  | 2021-02-18 07:37:54.678 | [     0.003084s]  INFO ThreadId(01) outbound: linkerd_app: listen.addr=127.0.0.1:4140 ingress_mode=false

  | 2021-02-18 07:37:54.667 | time="2021-02-18T06:37:54Z" level=info msg="running version edge-21.1.2"

  | 2021-02-18 07:37:54.667 | time="2021-02-18T06:37:54Z" level=info msg="Found pre-existing key: /var/run/linkerd/identity/end-entity/key.p8"

  | 2021-02-18 07:37:54.667 | time="2021-02-18T06:37:54Z" level=info msg="Found pre-existing CSR: /var/run/linkerd/identity/end-entity/csr.der"

  | 2021-02-18 07:37:40.209 | [ 46231.770007s]  INFO ThreadId(02) daemon:tap:accept{peer.addr=10.250.145.146:39570 target.addr=10.250.149.30:4190}: linkerd_app_core::serve: Connection closed error=http2 error: protocol error: unspecific protocol error detected

  | 2021-02-18 07:37:40.209 | [ 46231.769678s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.145.146:37702 target.addr=10.250.149.30:4143}: linkerd_app_core::serve: Connection closed error=Direct connections must be mutually authenticated

  | 2021-02-18 07:37:40.209 | [ 46231.770379s]  INFO ThreadId(02) daemon:tap:accept{peer.addr=10.250.145.146:39574 target.addr=10.250.149.30:4190}: linkerd_app_core::serve: Connection closed error=http2 error: protocol error: unspecific protocol error detected

  | 2021-02-18 07:37:40.205 | [ 46231.765853s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.145.146:37678 target.addr=10.250.149.30:4143}: linkerd_app_core::serve: Connection closed error=Direct connections must be mutually authenticated
```

I noticed there are some errors related to mutual tls so I thought there might have been an issuer certificate rotation for `identity` happening at that time. We manage that certificate with cert-manager and the last rotation seems to have happened a while ago:
```
Status:
  Conditions:
    Last Transition Time:  2020-12-08T08:57:24Z
    Message:               Certificate is up to date and has not expired
    Reason:                Ready
    Status:                True
    Type:                  Ready
  Not After:               2021-04-07T08:57:23Z
```

Let me know if you need more information.

**Comment by olix0r** [comment]
OK, thanks for the clarification

First off, I'd suggest updating your branch to pull in the recent 2.133.0 tag, or at lease https://github.com/linkerd/linkerd2-proxy/commit/0495fc7e52ed5d4867eadd87e76694a61508495a; this should hopefully stop loop-induced OOMing, even if we haven't figured out the underlying cause. I'd also recommend using the latest edge control plane, which includes the informer fixes you submitted.

>  > If this output is from the sp-validator component, this is especially confusing, as, as far as i know, there shouldn't ever be outbound connections from this controller.

> Could this be indicating a connection failure to other control plane components like destination and identity? We've had several data plane issues caused by failures in destination. It might also be the reason why the container lives for such a short time, just a bit longer than a minute.

I don't *think* so. On the inbound side, discovery isn't used for connection routing; and on the outbound side, connections will fail if discovery isn't performed. So the destination controller would have to serve _incorrect_ data to get ino this sort of situation.

These logs raise some concerns:

```
  | 2021-02-18 07:38:13.585 | [    18.909286s]  INFO ThreadId(01) inbound:accept{peer.addr=10.250.145.146:56676 target.addr=10.250.149.30:4143}: linkerd_app_core::serve: Connection closed error=Direct connections must be mutually authenticated
```

This error indicates that the pod got a connection on port 4143 (either the client connected directly to 4143 or the `SO_ORIGINAL_DST` socket option failed -- but I would expect errors to be logged in the latter case).  Under normal operation, I would not expect pods--especially the sp-validator--to get connections on port 4143. Do you happen to know what pod was at `10.250.145.146`? Do you have port scanners in your system that connect to arbitrary ports?

Once you run the latest proxy--that should hopefully eliminate these OOMs--it would be helpful to get more detailed logs--for instance via `linkerd upgrade --proxy-log-level=linkerd=debug,warn` or by setting pod spec annotations like `config.linkerd.io/proxy-log-level: linkerd=debug.warn`).

**Comment by fpetkovski** [comment]
You were right, we have a twistlock pod (a container security software) running with that IP address and it was probably trying to connect to 4143.

Regarding the OOMs, we can try out the new edge proxy version in the next week or so and I can report back if we continue seeing the issues. Thanks for the fast turnaround on this one.

**Comment by kleimkuhler** [comment]
@fpetkovski Just checking back in—I'm wondering if you had the chance to try out the new edge and if you've run into any OOM issues?

**Comment by fpetkovski** [comment]
Hey @kleimkuhler, thanks for following up. I am off this week and we haven't tried out the new version yet. However, we can test it next week and I will come back with feedback on whether it solves the issue for us.

**Comment by kleimkuhler** [comment]
Sounds good enjoy your off-week! I'll keep an eye out for an update when you get around to it.

**Comment by fpetkovski** [comment]
@kleimkuhler we have been running the edge version of the proxy for a week now and we haven't noticed any OOM issues. I think it's safe to say that the commit solved our problem. We can reopen a new issue with more information if the problem happens again.

**Comment by kleimkuhler** [comment]
Great to hear @fpetkovski thanks for the update.

**Comment by shahriak** [comment]
Is this issue fixed in the stable 2.10.0 version? I am facing a similar issue..

**Comment by kleimkuhler** [comment]
@shahriak I'd recommend using stable 2.10.1 since that is the more recent stable that fixed some issues we found soon after releasing 2.10.

As for this specific issue, we had a few ideas on what it was but I don't think we ever could say exactly what fixed the issue. That being said, we haven't seen many other OOM issues recently so I think you should be okay upgrading. If you do run into an issue like this though, you should definitely open a new issue with a fresh description and we'll look into it ASAP.

**Comment by kleimkuhler** [comment]
Sorry I meant recommend stable 2.10.2!

**Comment by shahriak** [comment]
> @shahriak I'd recommend using stable 2.10.1 since that is the more recent stable that fixed some issues we found soon after releasing 2.10.
> 
> As for this specific issue, we had a few ideas on what it was but I don't think we ever could say exactly what fixed the issue. That being said, we haven't seen many other OOM issues recently so I think you should be okay upgrading. If you do run into an issue like this though, you should definitely open a new issue with a fresh description and we'll look into it ASAP.

Thank you! Upgrading to 2.10.2 version resolved the issue! :)

**Comment by kleimkuhler** [comment]
@shahriak Ah great to hear! I saw your discussion about it #6231. Is that solved now as well?

**Comment by shahriak** [comment]
> @shahriak Ah great to hear! I saw your discussion about it #6231. Is that solved now as well?

Actually, I am still seeing the same issue in 2.10.2 version as well.

**Comment by kleimkuhler** [comment]
@shahriak Ah sorry to hear that. Would you please open a new issue with as much detail as you can provide, and possibly steps for reproducing this? I know you opened the discussion and there is some overlap with issues and discussions, but this can be better tracked as a new issue.
