### ISSUE TITLE
Dropped connections between fluentd forwarder and aggregator pods

### ISSUE THREAD

**Issue by irizzant** [linkerd/linkerd2#5880]
Hi all,
I have problems deploying elasticsearch (ECK) version 1.4 with fluentd and linkerd enabled.

Linkerd version is 2.9.4.

ECK was deployed with [these instructions](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-linkerd.html).

Fluentd was deployed using [this chart](https://github.com/bitnami/charts/tree/master/bitnami/fluentd) with a forwarder/aggregator configuration.

I get a bunch of connection reset by peer errors in linkerd-proxy logs.
I have both ECK and fluentd with linkerd injection enabled.

ECK cluster is assembled and looks like it's working just fine:
```
NAME             HEALTH  NODES  VERSION  PHASE  AGE
elastic-cluster  green   3      7.11.1   Ready  87m
NAME    HEALTH  NODES  VERSION  AGE
kibana  green   1      7.11.1   90m
```

Fluentd is deployed with forwarder/aggregator.
As soon as the forwarder starts sending data to aggregator I get aggregator's linkerd-proxy container logging a bunch of:

```
[ 3198.466580s] INFO ThreadId(01) inbound:accept{peer.addr=10.42.0.73:42184 target.addr=10.42.0.66:24224}: 
linkerd2_app_core::serve: Connection closed error=Connection reset by peer (os error 104)
```

The same stack works just fine without linkerd enabled.

Here's the [link](https://linkerd.slack.com/archives/C89RTCWJF/p1615223224045200) to the discussion in Slack.

Adding the annotations at namespace level to skip port 24224 resolves the issue, but leaves the connection not encrypted.

After updating to linkerd edge-21.3.1 and removing the annotations to skip the port, the stack is working just fine.

What's surprising here is that adding the annotation at namespace level to configure port 24224 as opaque like this:
```
config.linkerd.io/opaque-ports: 24224
```
causes the connection between forwarder and aggregator drop again:
```
[   38.584553s] INFO ThreadId(01) outbound:accept{client.addr=10.42.0.130:41716 target.addr=10.42.0.128:24224}: linkerd_app_core::serve: Connection closed error=request timed out
```
Where:
```
NAME           READY  STATUS   RESTARTS  AGE    IP           NODE               NOMINATED NODE  READINESS GATES
fluentd-1      2/2    Running  0         2m24s  10.42.0.128  k3d-test-server-0  <none>          <none>
fluentd-0      2/2    Running  0         2m4s   10.42.0.129  k3d-test-server-0  <none>          <none>
fluentd-mwvfk  2/2    Running  0         114s   10.42.0.130  k3d-test-server-0  <none>          <none>
```
Moreover the aggregator now receives broken data:
```
2021-03-09 08:31:23 +0000 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=114
2021-03-09 08:31:23.169435292 +0000 fluent.warn: {"host":"127.0.0.1","msg":74,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=74"}
2021-03-09 08:31:23 +0000 [warn]: #0 incoming chunk is broken: host="127.0.0.1" msg=28
2021-03-09 08:31:23.169487107 +0000 fluent.warn: {"host":"127.0.0.1","msg":114,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=114"}
2021-03-09 08:31:23.169542587 +0000 fluent.warn: {"host":"127.0.0.1","msg":28,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=28"}
```

**Comment by kleimkuhler** [comment]
@irizzant Would you be able to try this again with the new edge `edge-21.3.2`? We fixed an issue where non-HTTP streams could sometimes hang and that may be the cause for the broken chunks.

**Comment by irizzant** [comment]
@kleimkuhler ok I'm going to try and let you know

**Comment by irizzant** [comment]
That did not fix the issue.
```
linkerd version 
Client version: edge-21.3.2
Server version: edge-21.3.2
```

Fluentd namespace is correctly annotated:
```
Name:         fluentd
Labels:       <none>
Annotations:  config.linkerd.io/opaque-ports: 24224
              linkerd.io/inject: enabled
Status:       Active

No resource quota.

No LimitRange resource.
```

The connection between forwarder and aggregator is still dropping.
See logs from forwarder's `linkerd-proxy`
```
[    35.487768s]  INFO ThreadId(01) outbound:accept{client.addr=10.42.0.36:58108 target.addr=10.42.0.33:24224}: linkerd_app_core::serve: Connection closed error=request timed out
[    35.499297s]  INFO ThreadId(01) outbound:accept{client.addr=10.42.0.36:58120 target.addr=10.42.0.33:24224}: linkerd_app_core::serve: Connection closed error=request timed out
```
Where the IPs are:
```
NAME            READY   STATUS    RESTARTS   AGE     IP           NODE                NOMINATED NODE   READINESS GATES
fluentd-0       2/2     Running   0          13m     10.42.0.33   k3d-test-server-0   <none>           <none>
fluentd-1       2/2     Running   0          6m18s   10.42.0.35   k3d-test-server-0   <none>           <none>
fluentd-49f85   2/2     Running   0          4m29s   10.42.0.36   k3d-test-server-0   <none>           <none>
```
And fluentd-0 packets are broken:
```
}
2021-03-10 21:26:17.253379386 +0000 fluent.warn: {"host":"127.0.0.1","msg":46,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=46"}
2021-03-10 21:26:17.253419248 +0000 fluent.warn: {"host":"127.0.0.1","msg":108,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=108"}
2021-03-10 21:26:17.253453286 +0000 fluent.warn: {"host":"127.0.0.1","msg":105,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=105"}
2021-03-10 21:26:17.253482972 +0000 fluent.warn: {"host":"127.0.0.1","msg":110,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=110"}
2021-03-10 21:26:17.253510101 +0000 fluent.warn: {"host":"127.0.0.1","msg":107,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=107"}
2021-03-10 21:26:17.253542294 +0000 fluent.warn: {"host":"127.0.0.1","msg":101,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=101"}
2021-03-10 21:26:17.253574825 +0000 fluent.warn: {"host":"127.0.0.1","msg":114,"message":"incoming chunk is broken: host=\"127.0.0.1\" msg=114"}
```

**Comment by kleimkuhler** [comment]
@irizzant Okay thanks for the update we'll keep looking into this.

**Comment by adleong** [comment]
Thanks @irizzant!  This is pretty weird.  Are you able to share full logs from the the forwarder's Linkerd proxy and the aggregator's Linkerd proxy?  Ideally, first setting the proxy log-level to `linkerd=debug,info`.  This should give us some additional context about what might be happening here.

**Comment by irizzant** [comment]
Will definitively do @adleong , thanks

**Comment by olix0r** [comment]
> What's surprising here is that adding the annotation at namespace level to configure port 24224 as opaque like this:
> ```
> config.linkerd.io/opaque-ports: 24224
> ```

Out of curiosity, can you try setting this annotation directly on your pod specs rather than the namespace? This may be related to #5736

**Comment by irizzant** [comment]
Ok, here are the linkerd-proxy logs from forwarder:
```
[    92.622944s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44814 target.addr=10.42.0.29:24224}:tcp:tcp.forward{server.addr=10.42.0.29:24224}: linkerd_proxy_transport::connect: Connected local.addr=10.42.0.28:44816 keepalive=Some(10s)
[    92.622960s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44814 target.addr=10.42.0.29:24224}:tcp:tcp.forward{server.addr=10.42.0.29:24224}: rustls::client::hs: No cached session for DNSNameRef("default.fluentd.serviceaccount.identity.linkerd.cluster.local")    
[    92.622967s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44814 target.addr=10.42.0.29:24224}:tcp:tcp.forward{server.addr=10.42.0.29:24224}: rustls::client::hs: Not resuming any session    
[    93.247739s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}: tower::buffer::worker: service.ready=true processing request
[    93.247862s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}: linkerd_proxy_http::detect: Could not detect protocol read=0
[    93.247895s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}: linkerd_detect: DetectResult protocol=None elapsed=72.366µs
[    93.247927s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}:tcp: linkerd_app_outbound::target: Target is unresolveable reason=not_provided_by_service_discovery orig_dst=10.42.0.29:24224
[    93.248047s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}:tcp:tcp.forward{server.addr=10.42.0.29:24224}: linkerd_tls::client: Initiating TLS connection server.id=default.fluentd.serviceaccount.identity.linkerd.cluster.local
[    93.248071s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}:tcp:tcp.forward{server.addr=10.42.0.29:24224}: linkerd_proxy_transport::connect: Connecting server.addr=10.42.0.29:24224
[    93.248405s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}:tcp:tcp.forward{server.addr=10.42.0.29:24224}: linkerd_proxy_transport::connect: Connected local.addr=10.42.0.28:44830 keepalive=Some(10s)
[    93.248466s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}:tcp:tcp.forward{server.addr=10.42.0.29:24224}: rustls::client::hs: No cached session for DNSNameRef("default.fluentd.serviceaccount.identity.linkerd.cluster.local")    
[    93.248486s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}:tcp:tcp.forward{server.addr=10.42.0.29:24224}: rustls::client::hs: Not resuming any session    
[    93.252969s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.28:44828 target.addr=10.42.0.29:24224}: linkerd_app_core::serve: Connection closed reason=tls handshake eof
[    93.623995s]  INFO ThreadId(01) outbound:accept{client.addr=10.42.0.28:44814 target.addr=10.42.0.29:24224}: linkerd_app_core::serve: Connection closed error=request timed out
```

In order for you to be able to run the tests, I attach here the manifests used and here's the procedure to use them:
1. install linkerd (last edge version)
2. create a fluentd namespace with the namespace.yaml file
3. helm repo add bitnami https://charts.bitnami.com/bitnami
4. helm install fluentd -f values.yaml -n fluentd bitnami/fluentd

The attached values.yaml already adds the linkerd-proxy log level to debug.
Hope it helps.
[tmp.tar.gz](https://github.com/linkerd/linkerd2/files/6167413/tmp.tar.gz)

**Comment by dadjeibaah** [comment]
I looked into this all little and there are a few things that stood out to me.

- The `forwarder` which is sending requests to the `aggregator` is logging `Connection closed reason=tls handshake eof` which leads me to believe TLS isn't working the way we expect between the forwarder's client proxy and the aggregators server proxy.
- I notice that the `aggregator` indeed receives request from the `forwarder`, but they get sent to the aggregator app on port 24224. Could it be that the the request is bypassing the proxy? Is this trying to establish a TLS handshake on that port?
```
[  2933.094380s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.8:59342}:server{port=24224}: linkerd_app_inbound::prevent_loop: addr=10.42.1.8:24224 self.port=4143
[  2933.094510s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.8:59342}:server{port=24224}:forward:tcp: linkerd_proxy_transport::connect: Connecting server.addr=127.0.0.1:24224
[  2933.094604s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.8:59342}:server{port=24224}:forward:tcp: linkerd_proxy_transport::connect: Connected local.addr=127.0.0.1:46320 keepalive=None
[  2933.094620s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.8:59342}:server{port=24224}:forward:tcp: linkerd_proxy_transport::metrics: client connection open
[  2933.100680s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.8:59342}: linkerd_app_core::serve: Connection closed reason=client: Connection reset by peer (os error 104)
[  2933.100777s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.8:59208}: linkerd_app_core::serve: Connection closed reason=client: Connection reset by peer (os error 104)
```

- I tried to verify if the app is TLS'd on that port by running from within the `aggregator` container and I don't think it is:
```bash
openssl s_client 127.0.0.1:24224
CONNECTED(00000003)
```
My understanding of this ^ command is that it will print out cert info if the connection is indeed TLS.

@olix0r does this make sense to you, or am I way off

**Comment by olix0r** [comment]
@dadjeibaah thanks! at a glance, this sounds likely related to an issue we fixed last week (https://github.com/linkerd/linkerd2/issues/5948) -- it would be good to test this again once this week's edge release is out or with the workload annotations:
```
        config.linkerd.io/proxy-image: ghcr.io/olix0r/l2-proxy
        config.linkerd.io/proxy-version: tls-detect.dd75b4c5
```

**Comment by dadjeibaah** [comment]
@olix0r, @irizzant I've ran the reproduction steps and used the latest edge (edge-21.4.1) and I think this issue has been fixed. I no longer see the `tls handshake` errors and can see forwarded logs in the aggregator.
```bash
 fluentd 2021-04-01 21:19:29.125345569 +0000 kubernetes.var.log.containers.random-logger_default_random-logger-b96791fdca30c79ede67a0062856e9dd9f932fddcae4aeb8e6546e178336ff59.log: {"timestamp":"2021-04-01T21:19:28.374631946Z","stream":"stdout","partial_flag":"F","message":"20 │
│ 21-04-01T21:19:28+0000 ERROR An error is usually an exception that has been caught and not handled.","docker":{"container_id":"b96791fdca30c79ede67a0062856e9dd9f932fddcae4aeb8e6546e178336ff59"},"kubernetes":{"container_name":"random-logger","namespace_name":"default","pod_nam │
│ e":"random-logger","container_image":"docker.io/chentex/random-logger:latest","container_image_id":"docker.io/chentex/random-logger@sha256:7cae589926ce903c65a853c22b4e2923211cc19966ac8f8cc533bbcff335ca39","pod_id":"6b30c435-3e5d-4b6c-8fad-2c6178fd9414","host":"k3d-repro-serve │
│ r-0","master_url":"https://10.43.0.1:443/api","namespace_id":"95b0efaf-56ba-40fb-a7ff-695f3eda8995"}}                                                                                                                                                                                │
│ fluentd 2021-04-01 21:19:30.124992520 +0000 kubernetes.var.log.containers.random-logger_default_random-logger-b96791fdca30c79ede67a0062856e9dd9f932fddcae4aeb8e6546e178336ff59.log: {"timestamp":"2021-04-01T21:19:30.048797268Z","stream":"stdout","partial_flag":"F","message":"20 │
│ 21-04-01T21:19:30+0000 DEBUG This is a debug log that shows a log that can be ignored.","docker":{"container_id":"b96791fdca30c79ede67a0062856e9dd9f932fddcae4aeb8e6546e178336ff59"},"kubernetes":{"container_name":"random-logger","namespace_name":"default","pod_name":"random-lo │
│ gger","container_image":"docker.io/chentex/random-logger:latest","container_image_id":"docker.io/chentex/random-logger@sha256:7cae589926ce903c65a853c22b4e2923211cc19966ac8f8cc533bbcff335ca39","pod_id":"6b30c435-3e5d-4b6c-8fad-2c6178fd9414","host":"k3d-repro-server-0","master_ │
│ url":"https://10.43.0.1:443/api","namespace_id":"95b0efaf-56ba-40fb-a7ff-695f3eda8995"}}                                                                                                                                                                                             │
│ fluentd 2021-04-01 21:19:32.124151623 +0000 kubernetes.var.log.containers.random-logger_default_random-logger-b96791fdca30c79ede67a0062856e9dd9f932fddcae4aeb8e6546e178336ff59.log: {"timestamp":"2021-04-01T21:19:31.189961131Z","stream":"stdout","partial_flag":"F","message":"20 │
│ 21-04-01T21:19:31+0000 INFO This is less important than debug log and is often used to provide context in the current task.","docker":{"container_id":"b96791fdca30c79ede67a0062856e9dd9f932fddcae4aeb8e6546e178336ff59"},"kubernetes":{"container_name":"random-logger","namespace_ │
│ name":"default","pod_name":"random-logger","container_image":"docker.io/chentex/random-logger:latest","container_image_id":"docker.io/chentex/random-logger@sha256:7cae589926ce903c65a853c22b4e2923211cc19966ac8f8cc533bbcff335ca39","pod_id":"6b30c435-3e5d-4b6c-8fad-2c6178fd9414" │
│ ,"host":"k3d-repro-server-0","master_url":"https://10.43.0.1:443/api","namespace_id":"95b0efaf-56ba-40fb-a7ff-695f3eda8995"}}                                                                                                                                                        │
│ fluentd 2021-04-01 21:19:33.124789883 +0000 kubernetes.var.log.containers.random-logger_default_random-logger-b96791fdca30c79ede67a0062856e9dd9f932fddcae4aeb8e6546e178336ff59.log: {"timestamp":"2021-04-01T21:19:32.929815015Z","stream":"stdout","partial_flag":"F","message":"20 │
│ 21-04-01T21:19:32+0000 INFO This is less important than debug log and is often used to provide context in the current task.","docker":{"container_id":"b96791fdca30c79ede67a0062856e9dd9f932fddcae4aeb8e6546e178336ff59"},"kubernetes":{"container_name":"random-logger","namespace_ │
│ name":"default","pod_name":"random-logger","container_image":"docker.io/chentex/random-logger:latest","container_image_id":"docker.io/chentex/random-logger@sha256:7cae589926ce903c65a853c22b4e2923211cc19966ac8f8cc533bbcff335ca39","pod_id":"6b30c435-3e5d-4b6c-8fad-2c6178fd9414" │
│ ,"host":"k3d-repro-server-0","master_url":"https://10.43.0.1:443/api","namespace_id":"95b0efaf-56ba-40fb-a7ff-695f3eda8995"}}
```
It would be good to test this out on your end @irizzant to confirm that this is fixed.

**Comment by irizzant** [comment]
@dadjeibaah Thanks, I'm going to try and let you know

**Comment by irizzant** [comment]
@dadjeibaah  I confirm the last edge release is working as expected on my side too, thank you

**Comment by kleimkuhler** [comment]
@irizzant It was just released yesterday in `edge-21.4.1` which is a candidate for `stable-2.10.1`. We'll make the call early next week on if we need another edge or if we'll release the new stable next week.

**Comment by irizzant** [comment]
Ok @kleimkuhler thank you
